---
- name: Remove excessive software
  apt:
    name: "{{ packages }}"
    state: absent
    purge: true
  become: true
  vars:
    packages:
      - libreoffice*

- name: Give user access to the serial port
  user:
    name: "{{ ansible_user }}"
    groups: dialout
    append: yes
  become: true

- name: Install system essentials for the robot
  apt:
    name: "{{ packages }}"
  become: true
  vars:
    packages:
      - openssh-server
      - screen
      - ros-melodic-realsense2-camera
      - ros-melodic-librealsense2
      - ros-melodic-depthimage-to-laserscan

- name: Cleaning up launcher icons
  command: gsettings set org.gnome.shell favorite-apps "['firefox.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop']"
  become: false

