# Let NetworkManager manage all devices on this system
network:
  version: 2
  renderer: NetworkManager
  wifis:
    wlp58s0:
      dhcp4: no
      addresses:
        - 192.168.200.11/24
      access-points:
        "robotont-11":
          password: "12345678"
          mode: ap
          
          
# Let NetworkManager manage all devices on this system
network:
  version: 2
  renderer: NetworkManager
  ethernets:
    eno1:
      dhcp4: true
      optional: true
  wifis:
    wlp58s0:
      dhcp4: no
      dhcp6: no
      addresses: [192.168.200.{{ id }}/24]
      nameservers:
        addresses: [8.8.8.8]
      access-points:
        "robotont-{{ id }}":
          mode: ap
          password: "{{ wifi_pass }}"
