---
- name: Clean up build files in ~/catkin_ws
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "/home/{{ ansible_user }}/catkin_ws/build"
      - "/home/{{ ansible_user }}/catkin_ws/devel"
      - "/home/{{ ansible_user }}/catkin_ws/logs"

- name: make Catkin folders
  file:
    path: "/home/{{ ansible_user }}/catkin_ws/src"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0775'
  tags:
    - untested

#- name: Ensure group "somegroup" exists
#  ansible.builtin.group:
#    name: lapt
#    state: present

- name: Copy .rosinstall file with owner and permissions for laptop
  copy:
    src: files_for_laptops/.rosinstall
    dest: /home/{{ ansible_user }}/catkin_ws/src/.rosinstall
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  when: is_robot is not defined
    
- name: Copy .rosinstall file with owner and permissions for robot
  copy:
    src: files_for_robots/.rosinstall
    dest: /home/{{ ansible_user }}/catkin_ws/src/.rosinstall
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  when: is_robot is defined

  #when: ansible_default_ipv4.gateway is defined


  #  - name: Clone robotont Git into Catkin workspace
  #    git:
  #      repo: https://github.com/ut-ims-robotics/robotont.git
  #      dest: /home/{{ ansible_user }}/catkin_ws/src
  #      version: kinetic-devel
  #    become_user: "{{ ansible_user }}"
  #    tags:
  #      - untested

- name: Add ros default workspace to bashrc
  lineinfile:
    path: /home/{{ ansible_user }}/.bashrc
    line: source /opt/ros/noetic/setup.bash
  become_user: "{{ ansible_user }}"
  tags:
    - untested

- name: Update catkin workspace
  shell: bash -ic 'vcs import < .rosinstall'
  args:
    chdir: /home/{{ ansible_user }}/catkin_ws/src
  become_user: "{{ ansible_user }}"
  tags: untested


