---
- name: Clean up build files in ~/catkin_ws
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - "/home/{{ ansible_user }}/catkin_ws/build"
      - "/home/{{ ansible_user }}/catkin_ws/devel"
      - "/home/{{ ansible_user }}/catkin_ws/log"

- name: make Catkin folders
  file:
    path: "/home/{{ ansible_user }}/catkin_ws/src"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0775'
  tags:
    - untested

- name: Copy .rosinstall file with owner and permissions
  copy:
    src: files/.rosinstall
    dest: /home/{{ ansible_user }}/catkin_ws/src/.rosinstall
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

  #  - name: Clone robotont Git into Catkin workspace
  #    git:
  #      repo: https://github.com/ut-ims-robotics/robotont.git
  #      dest: /home/{{ ansible_user }}/catkin_ws/src
  #      version: kinetic-devel
  #    become_user: "{{ ansible_user }}"
  #    tags:
  #      - untested

- name: Add ros default workspace to bashrc
  lineinfile:
    path: /home/{{ ansible_user }}/.bashrc
    line: source /opt/ros/melodic/setup.bash
  become_user: "{{ ansible_user }}"
  tags:
    - untested

- name: Update catkin workspace
  shell: bash -ic 'vcs import < .rosinstall'
  args:
    chdir: /home/{{ ansible_user }}/catkin_ws
  become_user: "{{ ansible_user }}"
  tags: untested

- name: Build Catkin workspace for robotont
  shell: bash -ic 'catkin build'
  args: 
    chdir: /home/{{ ansible_user }}/catkin_ws 
  become_user: "{{ ansible_user }}"
  tags: untested

- name: Add catkin_ws to bashrc
  lineinfile:
    path: /home/{{ ansible_user }}/.bashrc
    line: source /home/{{ansible_user}}/catkin_ws/devel/setup.bash
  become_user: "{{ ansible_user }}"
  tags:
    - untested
