---
#Laptop specific configuration
#- name: Install system essentials for the laptop
#  apt:
#    name: "{{ packages }}"
#  become: true
#  vars:
#    packages:
#      - ros-noetic-realsense2-description
- name: Reconfiguring hostname 
  command: hostnamectl set-hostname laptop-{{ id }}
  become: true
  
- name: Install system essentials for the laptop
  apt:
    name: "{{ packages }}"
  become: true
  vars:
    packages:
      - ros-noetic-moveit
      - ros-noetic-moveit-visual-tools
      - ros-noetic-moveit-ros-planning-interface
      - ros-noetic-ros-control
      - ros-noetic-ros-controllers
      
- name: Update submodule step 1
  shell: git checkout eb2a4a14144a700ab1d64ef755dc8229cbe6553b
  args:
    chdir: /home/{{ ansible_user }}/catkin_ws/src/xarm_ros
  become_user: "{{ ansible_user }}"
  tags: untested

- name: Build Catkin workspace
  shell: bash -ic 'catkin build'
  args: 
    chdir: /home/{{ ansible_user }}/catkin_ws 
  become_user: "{{ ansible_user }}"
  tags: untested

- name: Add catkin_ws to bashrc
  lineinfile:
    path: /home/{{ ansible_user }}/.bashrc
    line: source /home/{{ansible_user}}/catkin_ws/devel/setup.bash
  become_user: "{{ ansible_user }}"
  tags:
    - untested
