---
#Laptop specific configuration
#- name: Install system essentials for the laptop
#  apt:
#    name: "{{ packages }}"
#  become: true
#  vars:
#    packages:
#      - ros-noetic-realsense2-description
- name: Reconfiguring hostname 
  command: hostnamectl set-hostname laptop-{{ id }}
  become: true
  
- name: Install system essentials for the laptop
  apt:
    name: "{{ packages }}"
  become: true
  vars:
    packages:
      - ros-noetic-moveit
      - ros-noetic-moveit-ros-move-group
      - ros-noetic-moveit-fake-controller-manager
      - ros-noetic-moveit-kinematics
      - ros-noetic-moveit-planners-ompl
      - ros-noetic-moveit-ros-visualization
      - ros-noetic-moveit-setup-assistant
      - ros-noetic-moveit-core
      - ros-noetic-moveit-ros-planning-interface
      - ros-noetic-moveit-ros-perception
      - ros-noetic-geometric-shapes
      - ros-noetic-moveit-visual-tools
      - ros-noetic-ros-controllers
      - ros-noetic-ros-control
      - python-numpy
      - ros-noetic-moveit-commander
      - ros-noetic-combined-robot-hw
