---
#Laptop specific configuration
#- name: Install system essentials for the laptop
#  apt:
#    name: "{{ packages }}"
#  become: true
#  vars:
#    packages:
#      - ros-noetic-realsense2-description
- name: Reconfiguring hostname 
  command: hostnamectl set-hostname laptop-{{ id }}
  become: true
