---
- hosts: robots
  remote_user: "{{ ansible_user }}"
  tasks:

  - name: Install dependencies needed for mapping and navigation.
    apt:
      update_cache: true
      name: "{{ packages }}"
    become: true
    vars:
      packages:
        - ros-melodic-rtabmap-ros
        - ros-melodic-cartographer-ros
        - ros-melodic-move-base
        - ros-melodic-gmapping

