---
- hosts: robots
  remote_user: "{{ ansible_user }}"

  tasks:
  - name: Set up a systemd service for Robotont
    template:
      src: robotont.service.j2
      dest: /lib/systemd/system/robotont.service
      owner: root
      group: root
      mode: '0644'
    become: true

  - name: Enable and start the service
    service:
      name: robotont.service
      state: started
      enabled: yes
    become: true
